### ISSUE TITLE
Wheel shape width/height adaption

### ISSUE THREAD

**Issue by alexscro** [uiwjs/react-color#110]
Hey everyone!

First of all, I love the library. Is there a way to change the width/height of the Wheel variant but not use a square?
I am able to change it with the props but the draggable picker still always seems to rotate in a circle?

I'd appreciate any help here!

<img width="169" alt="Screenshot 2023-03-31 at 19 05 42" src="https://user-images.githubusercontent.com/36740862/229184920-5f83fe1f-f41f-4269-9969-abcc3e858237.png">

**Comment by jaywcjlove** [comment]
@alexscro I tested it and it wasn't very good at handling this situation. If you have a solution, please feel free to contribute a PR.

**Comment by farshad-vgr** [comment]
> Hey everyone!
> 
> First of all, I love the library. Is there a way to change the width/height of the Wheel variant but not use a square? I am able to change it with the props but the draggable picker still always seems to rotate in a circle?
> 
> I'd appreciate any help here!
> 
> <img alt="Screenshot 2023-03-31 at 19 05 42" width="169" src="https://user-images.githubusercontent.com/36740862/229184920-5f83fe1f-f41f-4269-9969-abcc3e858237.png">

Use scaleY to change dimensions
style={{
        transform: "scaleY(0.5)",
      }}
