### ISSUE TITLE
Direction hue "vertical"

### ISSUE THREAD

**Issue by Lbdevaa** [uiwjs/react-color#126]
Is it possible to implement direction="vertical"?

**Comment by jaywcjlove** [comment]
@Lbdevaa Is that component?

**Comment by Lbdevaa** [comment]
> @Lbdevaa Is that component?

`<Hue
    direction="vertical"
    hue={hsva.h}
    onChange={newHue => {
        setHsva({...hsva, ...newHue});
    }}
/>`
