### ISSUE TITLE
Support hex input with leading #

### ISSUE THREAD

**Issue by cbn-falias** [uiwjs/react-color#130]
It would be great, if values like `#121212` could also be pasted into the hex input fields.
When copying a hex value from an arbitrary source it might contain a leading `#`.
When pasting it into the input field it unfortunately resets to the previous value.

![image](https://github.com/uiwjs/react-color/assets/66297925/e03b81dc-d673-476a-a5c0-ac0ea67caf56)

**Comment by jaywcjlove** [comment]
@cbn-falias Upgrade `v1.4.3`

**Comment by cbn-falias** [comment]
Works like a charm!
Thank you so much for this super fast release. 😊🚀
