### ISSUE TITLE
Typo in Github picker placement enum: "Botton" instead of "Bottom" 

### ISSUE THREAD

**Issue by manuel-mauky** [uiwjs/react-color#131]
In the `GithubPlacement` enum there is a typo the word "Bottom" in several combinations.

```
export enum GithubPlacement {
  Left = 'L',
  LeftTop = 'LT',
  LeftBotton = 'LB',
  Right = 'R',
  RightTop = 'RT',
  RightBotton = 'RB',
  Top = 'T',
  TopRight = 'TR',
  TopLeft = 'TL',
  Botton = 'B',
  BottonLeft = 'BL',
  BottonRight = 'BR',
}
```

Not sure if you want to change this as it would mean a API breaking change. You could add the correctly spelled keys mapping to the same string values though.

**Comment by jaywcjlove** [comment]
@manuel-mauky update `v2.0.0`
