### ISSUE TITLE
Sometimes Wheel don't react to onChange

### ISSUE THREAD

**Issue by spl1nt3r99** [uiwjs/react-color#134]
I've used code like this:

```
const [hsva, setHsva] = useState({ h: 214, s: 43, v: 90, a: 1 })

const onChangeColorPicker = (event: any) => {
    setHsva({ ...hsva, ...event.hsva })
  }
  
return (
 <Wheel className={"wheel"} color={hsva} onChange={(event) => onChangeColorPicker(event)} />
)
```

At times, when I simply click (**not click, hold, and move**) on the wheel, the color doesn't update immediately. I find that I have to click on the same spot again to trigger the onChange event.
Do I need to use another approach?

**Comment by jaywcjlove** [comment]
<img width="816" alt="image" src="https://github.com/uiwjs/react-color/assets/1680273/2967b729-1334-4df6-9d1e-cd8bfcf213f6">

@spl1nt3r99 I can't reproduce the problem you describe.

You can give me an example that can be reproduced
