### ISSUE TITLE
[color-convert] Circular dependencies error

### ISSUE THREAD

**Issue by piotrkulpinski** [uiwjs/react-color#137]
Hi,

I'm trying to bundle a project using `@uiw/color-convert` package, but I get the `Circular dependencies` error.

```
(!) Circular dependencies
node_modules/@uiw/color-convert/esm/index.js -> node_modules/@uiw/color-convert/esm/utils.js -> node_modules/@uiw/color-convert/esm/index.js
node_modules/@uiw/color-convert/esm/index.js -> node_modules/@uiw/color-convert/esm/getContrastingColor.js -> node_modules/@uiw/color-convert/esm/index.js
```

Anyone had any issue like that? Trying to find out if it's a bug or am I doing something wrong.
Thanks

**Comment by jaywcjlove** [comment]
@piotrkulpinski You can try `v2.0.5` to see if the problem is solved.

**Comment by piotrkulpinski** [comment]
@jaywcjlove This seems to be fixing this issue! Thanks.
