### ISSUE TITLE
Add eyedropper to Chrome

### ISSUE THREAD

**Issue by dumbmatter** [uiwjs/react-color#148]
Chrome's actual color picker widget has an eye dropper to let you pick any color. Chrome actually has an API to let you easily add that functionality https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper - although it won't work in any other browsers, unfortunately. Might still be worth adding, you can do feature detection to decide whether to show it or not.

**Comment by jaywcjlove** [comment]
@dumbmatter Upgrade `v2.2.0`
