### ISSUE TITLE
Wheel cursor disabled

### ISSUE THREAD

**Issue by NerdPraise** [uiwjs/react-color#149]
What happens: 
For the wheel component, if the color is set to '#000000', then the cursor is immovable

What should happen:
The cursor should be able to move round the wheel and maybe capture all essence of black

**Comment by jaywcjlove** [comment]
@NerdPraise Using `hsva` values will not cause this issue.

```jsx
<Wheel color={{a: 1, h: 214, s: 0, v: 40}} />
<Wheel color={{a: 1, h: 214, s: 0, v: 40}} width={100} height={100} />
```

https://github.com/uiwjs/react-color/blob/71617b3621f22c097cf34a2870009ff005ee7a5b/packages/color-convert/src/index.ts#L273-L274

https://github.com/uiwjs/react-color/blob/71617b3621f22c097cf34a2870009ff005ee7a5b/packages/color-convert/src/index.ts#L191

**Comment by NerdPraise** [comment]
Oh I see there is a `hextoHsva` utility function. Thank you so much. I would closed the issue
Appreciate the good work
