### ISSUE TITLE
Don't display editable input for alpha when pass argument showAlpha = false

### ISSUE THREAD

**Issue by NovitskiyGeorge** [uiwjs/react-color#159]
It will be great when we pass argument showAlpha = false don't display editable input for alpha. 
I use Chrome color in different places and in some places I don't need display alpha and I pass showAlpha = false, but editable input for alpha is displayed.
Please pay attention to this.

![chromeColor](https://github.com/user-attachments/assets/92afe362-73ff-481b-b074-9034ea4a0b84)

**Comment by jaywcjlove** [comment]
@NovitskiyGeorge Upgrade `v2.3.2`

**Comment by NovitskiyGeorge** [comment]
Wow, so fast. Thanks)
