### ISSUE TITLE
Circle Styles broken

### ISSUE THREAD

**Issue by ThomasPe** [uiwjs/react-color#161]
Since Version 2.1.1 the Circle control is not round anymore (as you can see from your demo site).

https://github.com/uiwjs/react-color/commit/26fce86292343a3fb780fbabddf5b165e760e340#diff-78915ef11843db5002f105e9d5a2e046fe3b84eb3e0e0bcc4be7caa550fb34d1R53
This change is most likely overriding the circle style

**Comment by jaywcjlove** [comment]
@ThomasPe thx! Upgraded to v2.3.3, the issue has been resolved.

**Comment by ThomasPe** [comment]
much appreciated
