### ISSUE TITLE
Feature request: Ability to disable alpha

### ISSUE THREAD

**Issue by PedroDNBR** [uiwjs/react-color#95]
It would be very nice to be able to pass a prop to the color picker to remove the alpha slider when I want to restrict the possible value selected to RGB, not RGBA. If the ability already exists, I have not managed to find it in the documentation.

I'm thinking it would work something like:
```
<Colorful disableAlpha='true' />
```

![image](https://user-images.githubusercontent.com/77301701/180665608-d949b673-f54b-41cf-8e40-c426afc923d4.png)

**Comment by jaywcjlove** [comment]
@PedroDNBR Upgrade `v1.1.0+`

```js
<Colorful disableAlpha={true} />
```
